<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto

namespace App\Grpc\Demo\DemoSrv;

/**
 * Protobuf type <code>demo.DemoSrv</code>
 */
interface DemoSrvInterface
{
    /**
     * Method <code>unary</code>
     *
     * @param \App\Grpc\Demo\DemoSrv\Req $request
     * @return \App\Grpc\Demo\DemoSrv\Reply
     */
    public function unary(\App\Grpc\Demo\DemoSrv\Req $request);

    /**
     * Method <code>serverStreaming</code>
     *
     * @param \App\Grpc\Demo\DemoSrv\Req $request
     * @return \App\Grpc\Demo\DemoSrv\Reply
     */
    public function serverStreaming(\App\Grpc\Demo\DemoSrv\Req $request);

    /**
     * Method <code>clientStreaming</code>
     *
     * @param \App\Grpc\Demo\DemoSrv\Req $request
     * @return \App\Grpc\Demo\DemoSrv\Reply
     */
    public function clientStreaming(\App\Grpc\Demo\DemoSrv\Req $request);

    /**
     * Method <code>bidirectional</code>
     *
     * @param \App\Grpc\Demo\DemoSrv\Req $request
     * @return \App\Grpc\Demo\DemoSrv\Reply
     */
    public function bidirectional(\App\Grpc\Demo\DemoSrv\Req $request);

}

